### ISSUE TITLE
"Move to Trash" is broken and Root analysis does not list symlinked files/directories

### ISSUE THREAD

**Issue by Mershl** [flathub/org.gnome.baobab#1]
Tested version:
September 1, 2020 - 3.34.1

Host system:
Fedora Silverblue 32.20200911.0

Observed issues:
- "Move to Trash" for files in the home folder removes the file from the view in "Disk Usage Analyzer" but not actually perform the remove to trash on the file system. No error messages are visible. The files are still present and will show up on the next run of the app.
- Root is listed with a wrong max size and analyzing root shows only non-symlinked files

512 GB drive shows 7,3GB available/7,3GB total:
![image](https://user-images.githubusercontent.com/520251/92992431-34e2eb80-f4eb-11ea-808b-6900903ca02f.png)

Analyzing root shows only a limited amount of files (possible Silverblue issue?):
![image](https://user-images.githubusercontent.com/520251/92992446-4c21d900-f4eb-11ea-94e8-11ccea2ebd0b.png)

**Comment by A6GibKm** [comment]
This is my fault, I had given the app read only access to the host filesystem, should be fixed after #2 is merged.

> Analyzing root shows only a limited amount of files (possible Silverblue issue?)

This is a flatpak issue, the app is seeing the /usr and /etc (for example) mounted inside the flatpak. I don't know if there is a way around this.

**Comment by A6GibKm** [comment]
Could you test #2? It seems it does not work. This is weird, even the Baobab from the Fedora repo is not working properly.

**Comment by Mershl** [comment]
Tested it. You are right. Setting host filesystem or removing Other files: host:ro does not fix the issue on my machine. Weird. Is it possible to run a flatpak seeing the stdout and stderr of the applications executeable? `flatpak run` does not seem to show any terminal output for baobab.

**Comment by A6GibKm** [comment]
flatpak 1.6.5 or 1.8.1? (default on Silverblue should be 1.6.5.)

**Comment by Mershl** [comment]
Tested with `flatpak-1.6.5`. Is it working for you?

**Comment by A6GibKm** [comment]
I am testing with someone else. We are both in 1.8.1 so it is good to know this is not a 1.8 vs 1.6 thing. The situation is the following, I just built upstream baobab  using GNOME builder and it is not working either.

Note that it deletes files just fine, just not folders.

**Comment by A6GibKm** [comment]
Found the issue: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1274. Credits: @refi64.

**Comment by A6GibKm** [comment]
See https://github.com/flatpak/xdg-desktop-portal/issues/518

**Comment by A6GibKm** [comment]
Fixed by #9, the patch should be removed once there is a glib point release and it reaches the runtime.
